### ISSUE TITLE
Preparing for inclusion in Wn's index

### ISSUE THREAD

**Issue by goodmami** [sinaahmadi/kurdnet#2]
I'm the maintainer of the [Wn](https://github.com/goodmami/wn) project and I'm looking to include KurdNet in the project index for the next release. Before I do, I have some suggestions, but feel free to ignore them as they are not necessary for inclusion in the index, but they can make things more useful and/or convenient.

1. Change the lexicon ID to `kurdnet` (or similar). The `ckbwn` ID is less memorable and less "branded" to this project, and it follows the ID scheme of the previous release of OMW despite it not being distributed by OMW. This way, when a user of Wn wants to download KurdNet, they can do:
   ```python
   >>> wn.download('kurdnet')
   ```
   instead of
   ```python
   >>> wn.download('ckbwn')
   ```

2. Build an [WN-LMF package](https://wn.readthedocs.io/en/latest/guides/lexicons.html#wn-lmf-files-packages-and-collections) for the release. This is basically a directory containing the XML file along with (optionally) a README, LICENSE, or citation.bib file. This is useful for distributing the full texts of these additional files along with the wordnet itself. If you don't wish to distribute these files, just the XML file is fine.

3. Compress the package or XML file and attach it to a release on GitHub (examples: [OMW v1.4](https://github.com/omwn/omw-data/releases/tag/v1.4), [OdeNet v1.4](https://github.com/hdaSprachtechnologie/odenet/releases/tag/v1.4)). I strongly recommend this one, as currently the `ckbwn.xml` file is checked into the repository directly, so it's not clear which commit corresponds to the released version. In other projects we have used GitHub Actions scripts to automate this process for us, and I can help you get this set up.

4. (Unrelated to packaging for Wn) The link at the bottom of https://sinaahmadi.github.io/resources/kurdnet.html says "Download KurdNet at https://github.com/klpp/kurdnet." but I think that link should refer to this repository instead.

Let me know if you have questions

**Comment by sinaahmadi** [comment]
Thanks, @goodmami, for your nice suggestions.
I guess I agree with all your points. Let me get back to you by the end of the week with a new version of the resource ;-)

Thanks!

**Comment by goodmami** [comment]
Great, for the GitHub Actions workflow, I suggest checking out what we use in for omw-data ([link](https://github.com/omwn/omw-data/blob/main/.github/workflows/release.yml)), and the related scripts it calls (although most of `build.sh` is unnecessary for you).

I also opened omwn/omw-data#23 so it would be easy for you to just use that `tsv2lmf.py` script directly, but I don't think I'll be able to get around to it until next week.

**Comment by sinaahmadi** [comment]
Thank you very much, @goodmami! Now, the repository is updated and a release is provided according to your suggestions.

**Comment by goodmami** [comment]
Great, thanks! I verified that the link works, so I'll add this to Wn's index now.
